"""new reactions

Revision ID: b50fbea105de
Revises: 270ffdbbd95e
Create Date: 2021-10-27 14:55:28.079983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b50fbea105de'
down_revision = '270ffdbbd95e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reaction', type_='foreignkey')
    op.drop_constraint(None, 'reaction', type_='foreignkey')
    op.drop_constraint(None, 'reaction', type_='foreignkey')
    op.drop_column('reaction', 'reply_id')
    op.drop_column('reaction', 'post_id')
    op.drop_column('reaction', 'comment_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reaction', sa.Column('comment_id', sa.INTEGER(), nullable=True))
    op.add_column('reaction', sa.Column('post_id', sa.INTEGER(), nullable=True))
    op.add_column('reaction', sa.Column('reply_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'reaction', 'post', ['post_id'], ['id'])
    op.create_foreign_key(None, 'reaction', 'reply', ['reply_id'], ['id'])
    op.create_foreign_key(None, 'reaction', 'comment', ['comment_id'], ['id'])
    # ### end Alembic commands ###
